# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bin_controller_pb2 as bin__controller__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bin_controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BinControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListBins = channel.unary_unary(
                '/vibesort.BinController/ListBins',
                request_serializer=bin__controller__pb2.ListBinsRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.ListBinsResponse.FromString,
                _registered_method=True)
        self.AddBin = channel.unary_unary(
                '/vibesort.BinController/AddBin',
                request_serializer=bin__controller__pb2.AddBinRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.BinResponse.FromString,
                _registered_method=True)
        self.RemoveBin = channel.unary_unary(
                '/vibesort.BinController/RemoveBin',
                request_serializer=bin__controller__pb2.RemoveBinRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.BinResponse.FromString,
                _registered_method=True)
        self.GetBinStatus = channel.unary_unary(
                '/vibesort.BinController/GetBinStatus',
                request_serializer=bin__controller__pb2.GetBinStatusRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.BinStatusResponse.FromString,
                _registered_method=True)
        self.UploadImage = channel.unary_unary(
                '/vibesort.BinController/UploadImage',
                request_serializer=bin__controller__pb2.UploadImageRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.UploadImageResponse.FromString,
                _registered_method=True)
        self.AnalyzeBrick = channel.unary_unary(
                '/vibesort.BinController/AnalyzeBrick',
                request_serializer=bin__controller__pb2.AnalyzeBrickRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.AnalyzeBrickResponse.FromString,
                _registered_method=True)
        self.StorePrompt = channel.unary_unary(
                '/vibesort.BinController/StorePrompt',
                request_serializer=bin__controller__pb2.StorePromptRequest.SerializeToString,
                response_deserializer=bin__controller__pb2.StorePromptResponse.FromString,
                _registered_method=True)


class BinControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListBins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveBin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBinStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBrick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorePrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BinControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListBins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBins,
                    request_deserializer=bin__controller__pb2.ListBinsRequest.FromString,
                    response_serializer=bin__controller__pb2.ListBinsResponse.SerializeToString,
            ),
            'AddBin': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBin,
                    request_deserializer=bin__controller__pb2.AddBinRequest.FromString,
                    response_serializer=bin__controller__pb2.BinResponse.SerializeToString,
            ),
            'RemoveBin': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveBin,
                    request_deserializer=bin__controller__pb2.RemoveBinRequest.FromString,
                    response_serializer=bin__controller__pb2.BinResponse.SerializeToString,
            ),
            'GetBinStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBinStatus,
                    request_deserializer=bin__controller__pb2.GetBinStatusRequest.FromString,
                    response_serializer=bin__controller__pb2.BinStatusResponse.SerializeToString,
            ),
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=bin__controller__pb2.UploadImageRequest.FromString,
                    response_serializer=bin__controller__pb2.UploadImageResponse.SerializeToString,
            ),
            'AnalyzeBrick': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBrick,
                    request_deserializer=bin__controller__pb2.AnalyzeBrickRequest.FromString,
                    response_serializer=bin__controller__pb2.AnalyzeBrickResponse.SerializeToString,
            ),
            'StorePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.StorePrompt,
                    request_deserializer=bin__controller__pb2.StorePromptRequest.FromString,
                    response_serializer=bin__controller__pb2.StorePromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vibesort.BinController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vibesort.BinController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BinController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListBins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/ListBins',
            bin__controller__pb2.ListBinsRequest.SerializeToString,
            bin__controller__pb2.ListBinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/AddBin',
            bin__controller__pb2.AddBinRequest.SerializeToString,
            bin__controller__pb2.BinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveBin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/RemoveBin',
            bin__controller__pb2.RemoveBinRequest.SerializeToString,
            bin__controller__pb2.BinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBinStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/GetBinStatus',
            bin__controller__pb2.GetBinStatusRequest.SerializeToString,
            bin__controller__pb2.BinStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/UploadImage',
            bin__controller__pb2.UploadImageRequest.SerializeToString,
            bin__controller__pb2.UploadImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBrick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/AnalyzeBrick',
            bin__controller__pb2.AnalyzeBrickRequest.SerializeToString,
            bin__controller__pb2.AnalyzeBrickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StorePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vibesort.BinController/StorePrompt',
            bin__controller__pb2.StorePromptRequest.SerializeToString,
            bin__controller__pb2.StorePromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
