# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: echo.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'echo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\tbenchmark\"\x1e\n\x0bPingRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"\x1f\n\x0cPingResponse\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x32?\n\x04\x45\x63ho\x12\x37\n\x04Ping\x12\x16.benchmark.PingRequest\x1a\x17.benchmark.PingResponseB\x0cZ\nbench/echob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\nbench/echo'
  _globals['_PINGREQUEST']._serialized_start=25
  _globals['_PINGREQUEST']._serialized_end=55
  _globals['_PINGRESPONSE']._serialized_start=57
  _globals['_PINGRESPONSE']._serialized_end=88
  _globals['_ECHO']._serialized_start=90
  _globals['_ECHO']._serialized_end=153
# @@protoc_insertion_point(module_scope)
